import {
    ADD_MEMO,
    EDIT_MEMO,
    DELETE_MEMO,
    TOGGLE_TYPE,
    REQUEST_MEMOS,
    RECEIVE_MEMOS,
    RECEIVE_ERROR_MEMOS,
    TOGGLE_VALIDATE_MEMOS
} from './MemosActionTypes'
import { CHANGE_SHOWN_TYPE } from './ShownTypeActionTypes'
import {
    ADD_USER,
    EDIT_USER,
    DELETE_USER,
    TOGGLE_ACTIVE_USER,
    REQUEST_USER,
    RECEIVE_USER,
    RECEIVE_ERROR_USER,
    TOGGLE_VALIDATE_USERS
} from './UserActionTypes'

export default {
    ADD_MEMO,
    EDIT_MEMO,
    DELETE_MEMO,
    TOGGLE_TYPE,
    REQUEST_MEMOS,
    RECEIVE_MEMOS,
    RECEIVE_ERROR_MEMOS,
    TOGGLE_VALIDATE_MEMOS,
    CHANGE_SHOWN_TYPE,
    ADD_USER,
    EDIT_USER,
    DELETE_USER,
    TOGGLE_ACTIVE_USER,
    REQUEST_USER,
    RECEIVE_USER,
    RECEIVE_ERROR_USER,
    TOGGLE_VALIDATE_USERS
}