const ADD_MEMO = 'ADD_MEMO',
    EDIT_MEMO = 'EDIT_MEMO',
    DELETE_MEMO = 'DELETE_MEMO',
    TOGGLE_TYPE = 'TOGGLE_TYPE',
    CHANGE_SHOWN_TYPE = 'CHANGE_SHOWN_TYPE';

export default {ADD_MEMO, EDIT_MEMO, DELETE_MEMO,TOGGLE_TYPE, CHANGE_SHOWN_TYPE}