const ADD_MEMO = 'ADD_MEMO',
    EDIT_MEMO = 'EDIT_MEMO',
    DELETE_MEMO = 'DELETE_MEMO',
    CHANGE_SHOWN_TYPE = 'CHANGE_SHOWN_TYPE';

export default {ADD_MEMO, EDIT_MEMO, DELETE_MEMO, CHANGE_SHOWN_TYPE}