export const ADD_MEMO = 'ADD_MEMO',
    EDIT_MEMO = 'EDIT_MEMO',
    DELETE_MEMO = 'DELETE_MEMO',
    REQUEST_MEMOS = 'REQUEST_MEMOS',
    RECEIVE_MEMOS = 'RECEIVE_MEMOS',
    RECEIVE_ERROR_MEMOS = 'RECEIVE_ERROR_MEMOS',
    INVALIDATE_MEMOS = 'INVALIDATE_MEMOS',
    TOGGLE_TYPE = 'TOGGLE_TYPE';