export const CHANGE_USER = 'CHANGE_USER',
    EDIT_USER = 'EDIT_USER',
    REQUEST_USER = 'REQUEST_USERS',
    RECEIVE_USER = 'RECEIVE_USERS',
    RECEIVE_ERROR_USER = 'RECEIVE_ERROR_USERS',
    TOGGLE_VALIDATE_USERS = 'TOGGLE_VALIDATE_USERS';